# Generated by Django 5.1.5 on 2026-08-12 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("store_enter", "입장"),
                            ("visit_start", "방문 시작"),
                            ("visit_end", "방문 종료"),
                            ("scene_view", "전시존 조회"),
                            ("scene_dwell", "전시존 체류"),
                            ("hotspot_click", "핫스팟 클릭"),
                            ("product_view", "상품 조회"),
                            ("product_dwell", "상품 체류"),
                            ("product_save", "상품 찜"),
                            ("chatbot_open", "챗봇 열기"),
                            ("question_submit", "질문 전송"),
                            ("recommendation_impression", "추천 노출"),
                            ("recommendation_click", "추천 클릭"),
                        ],
                        max_length=30,
                    ),
                ),
                ("client_timestamp", models.DateTimeField()),
                ("server_received_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="catalog.product",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="catalog.scene",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["visit", "event_type"],
                        name="events_even_visit_i_a945b1_idx",
                    ),
                    models.Index(
                        fields=["product", "event_type"],
                        name="events_even_product_eda9fc_idx",
                    ),
                ],
            },
        ),
    ]
