# Generated by Django 5.1.5 on 2026-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("store_enter", "입장"),
                    ("visit_start", "방문 시작"),
                    ("visit_end", "방문 종료"),
                    ("scene_view", "전시존 조회"),
                    ("scene_dwell", "전시존 체류"),
                    ("hotspot_click", "핫스팟 클릭"),
                    ("product_view", "상품 조회"),
                    ("product_dwell", "상품 체류"),
                    ("chatbot_open", "챗봇 열기"),
                    ("question_submit", "질문 전송"),
                    ("recommendation_impression", "추천 노출"),
                    ("recommendation_click", "추천 클릭"),
                    ("lookbook_candidates_view", "화보 후보 조회"),
                    ("lookbook_product_select", "화보 상품 선택"),
                    ("photo_consent", "사진 촬영 동의"),
                    ("photo_capture", "사진 촬영"),
                    ("photo_retake", "사진 재촬영"),
                    ("lookbook_generate_request", "화보 생성 요청"),
                    ("lookbook_regenerate", "화보 재생성"),
                    ("lookbook_complete", "화보 완성"),
                    ("lookbook_share", "화보 공유"),
                    ("lookbook_save", "화보 저장"),
                ],
                max_length=30,
            ),
        ),
    ]
