# Generated by Django 5.1.5 on 2026-08-12 06:26

import common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "slug",
                    models.CharField(
                        default=common.ids.gen_report_slug,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "분석 중"),
                            ("ready", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="visits.visit",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="visits.visitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TasteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", models.JSONField(default=dict)),
                ("axis_scores", models.JSONField(default=dict)),
                ("character_type", models.CharField(blank=True, max_length=4)),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_profile",
                        to="visits.visit",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_profiles",
                        to="visits.visitor",
                    ),
                ),
            ],
        ),
    ]
