# Generated by Django 5.1.5 on 2026-08-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="visitor",
        ),
        migrations.RemoveField(
            model_name="tasteprofile",
            name="visitor",
        ),
    ]
