# Generated by Django 5.1.5 on 2026-08-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_report_visitor_remove_tasteprofile_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('type_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('one_liner', models.CharField(max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type_code'],
            },
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='insight',
            field=models.JSONField(default=dict),
        ),
    ]
