# Generated by Django 5.1.5 on 2026-08-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_character_tasteprofile_insight"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Character",
        ),
        migrations.RemoveField(
            model_name="tasteprofile",
            name="axis_scores",
        ),
        migrations.RemoveField(
            model_name="tasteprofile",
            name="character_type",
        ),
    ]
