# Generated by Django 5.1.5 on 2026-08-18 09:11

import apps.lookbook.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0003_character_tasteprofile_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('min_face', models.FloatField()),
                ('max_face', models.FloatField()),
                ('reference_url', models.CharField(blank=True, max_length=300)),
                ('prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('share_slug', models.CharField(default=apps.lookbook.models.new_share_slug, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, default=apps.lookbook.models.new_job_id, editable=False, max_length=40)),
                ('attempt', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('queued', '대기'), ('processing', '생성 중'), ('ready', '완료'), ('failed', '실패')], default='queued', max_length=12)),
                ('product_ids', models.JSONField(default=list)),
                ('photo_key', models.CharField(max_length=200)),
                ('mask_key', models.CharField(blank=True, max_length=200)),
                ('mood_payload', models.JSONField(default=dict)),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lookbooks', to='lookbook.composition')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbooks', to='analysis.report')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('report', 'attempt'), name='uniq_report_attempt')],
            },
        ),
    ]
