# Generated by Django 5.1.5 on 2026-08-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbook',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lookbook',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
