# Generated by Django 5.1.5 on 2026-08-12 06:26

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.catalog.models.new_store_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.catalog.models.new_scene_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("no", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="catalog.store",
                    ),
                ),
            ],
            options={
                "ordering": ["no"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.catalog.models.new_product_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("no", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("price", models.PositiveIntegerField()),
                ("external_url", models.URLField()),
                ("story", models.TextField()),
                ("images", models.JSONField(default=list)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("backpack", "백팩"),
                            ("tote", "토트백"),
                            ("crossbody", "크로스백"),
                            ("shoulder", "숄더백"),
                            ("wallet", "지갑"),
                            ("accessory", "액세서리"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "블랙"),
                            ("white", "화이트"),
                            ("cognac", "코냑"),
                            ("beige", "베이지"),
                            ("navy", "네이비"),
                            ("red", "레드"),
                            ("pink", "핑크"),
                            ("metallic", "메탈릭"),
                            ("visetos_mix", "비세토스 배색"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("coated_canvas", "코팅 캔버스"),
                            ("smooth_leather", "스무스 레더"),
                            ("grained_leather", "그레인 레더"),
                            ("nylon", "나일론"),
                            ("suede", "스웨이드"),
                            ("mixed", "혼합"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("visetos_monogram", "비세토스 모노그램"),
                            ("logo_print", "로고 프린트"),
                            ("solid", "솔리드"),
                            ("studded", "스터드"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "silhouette",
                    models.CharField(
                        choices=[
                            ("structured", "구조적"),
                            ("slouchy", "슬라우치"),
                            ("boxy", "박시"),
                            ("compact", "컴팩트"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("classic_heritage", "클래식 헤리티지"),
                            ("minimal", "미니멀"),
                            ("y2k_street", "Y2K 스트리트"),
                            ("bold_statement", "볼드 스테이트먼트"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_band",
                    models.CharField(
                        choices=[
                            ("entry", "60만원 미만"),
                            ("mid", "60~120만원"),
                            ("high", "120만원 초과"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("daily", "데일리"),
                            ("work", "출근"),
                            ("travel", "여행"),
                            ("going_out", "나들이·모임"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_new", models.BooleanField(default=False)),
                ("attributes", models.JSONField(default=dict)),
                ("preset_answers", models.JSONField(default=dict)),
                ("llm_context", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["scene__no", "no"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "no"), name="uniq_scene_product_no"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.UniqueConstraint(
                fields=("store", "no"), name="uniq_store_scene_no"
            ),
        ),
    ]
