# Generated by Django 5.1.5 on 2026-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="muse_counter",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
