# Generated by Django 5.1.5 on 2026-08-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_cutout_url"),
        ("catalog", "0002_store_muse_counter"),
    ]

    operations = []
