# Generated by Django 5.1.5 on 2026-08-12 06:26

import apps.visits.models
import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "anonymous_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "age_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10s", "10대"),
                            ("20s", "20대"),
                            ("30s", "30대"),
                            ("40s", "40대"),
                            ("50s+", "50대 이상"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "여성"),
                            ("male", "남성"),
                            ("other", "기타"),
                            ("na", "응답 안 함"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.visits.models.new_visit_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=common.ids.gen_visit_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="catalog.store",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="visits.visitor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["visitor", "ended_at"],
                        name="visits_visi_visitor_8a2225_idx",
                    )
                ],
            },
        ),
    ]
