# Generated by Django 5.1.5 on 2026-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_remove_visit_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="age_band",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="gender",
        ),
        migrations.AddField(
            model_name="visit",
            name="age_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10s", "10대"),
                    ("20s", "20대"),
                    ("30s", "30대"),
                    ("40s", "40대"),
                    ("50s+", "50대 이상"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "여성"),
                    ("male", "남성"),
                    ("other", "기타"),
                    ("na", "응답 안 함"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="is_auto_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="muse_no",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
