# Generated by Django 5.1.5 on 2026-08-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_remove_visitor_age_band_remove_visitor_gender_and_more"),
        ("visits", "0003_visit_created_at"),
    ]

    operations = []
