# Generated by Django 5.1.5 on 2026-08-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatlog",
            name="updated_at",
        ),
    ]
